[build]
builder = "NIXPACKS"
buildCommand = "cp proxy-package.json package.json && npm install"

[deploy]
startCommand = "node proxy-server.cjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 