[build]
builder = "nixpacks"

# This tells Railway to use the root (client app) and ignore auth server
[build.watchPatterns]
include = ["client/**", "*.json", "*.ts", "*.js", "vite.config.ts", "tsconfig*.json"]
exclude = ["auth-server-openauth/**"]

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300

[environments.production]
[environments.production.build]
buildCommand = "npm install && npm run build"
startCommand = "npm run preview" 