use crate::items::{ItemDefinition, ItemCategory, CostIngredient};
use crate::models::{EquipmentSlotType, TargetType};

pub fn get_initial_item_definitions() -> Vec<ItemDefinition> {
    let initial_items = vec![
        // --- BASE RESOURCES ---
        ItemDefinition {
            id: 0,
            name: "Wood".to_string(),
            description: "A sturdy piece of wood. Good for fuel.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "wood.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: Some(5.0),
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone".to_string(),
            description: "A chunk of rock.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "stone.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Plant Fiber".to_string(),
            description: "Fibrous material from plants, used for making cloth.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "plant_fiber.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth".to_string(),
            description: "Woven fabric, used for basic clothing.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "cloth.png".to_string(),
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 5 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(1),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },

        // --- TOOLS ---
        ItemDefinition {
            id: 0,
            name: "Stone Hatchet".to_string(),
            description: "A simple hatchet for chopping wood.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "wood_hatchet.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(25),
            primary_target_damage_max: Some(35),
            primary_target_yield_min: Some(25),
            primary_target_yield_max: Some(35),
            primary_target_type: Some(TargetType::Tree),
            primary_yield_resource_name: Some("Wood".to_string()),
            secondary_target_damage_min: Some(3),
            secondary_target_damage_max: Some(7),
            secondary_target_yield_min: Some(3),
            secondary_target_yield_max: Some(7),
            secondary_target_type: Some(TargetType::Stone),
            secondary_yield_resource_name: Some("Stone".to_string()),
            pvp_damage_min: Some(15),
            pvp_damage_max: Some(15),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 75 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 25 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(10),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone Pickaxe".to_string(),
            description: "A simple pickaxe for breaking rocks.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "pick_axe.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(13),
            primary_target_damage_max: Some(22),
            primary_target_yield_min: Some(13),
            primary_target_yield_max: Some(22),
            primary_target_type: Some(TargetType::Stone),
            primary_yield_resource_name: Some("Stone".to_string()),
            secondary_target_damage_min: Some(3),
            secondary_target_damage_max: Some(7),
            secondary_target_yield_min: Some(3),
            secondary_target_yield_max: Some(7),
            secondary_target_type: Some(TargetType::Tree),
            secondary_yield_resource_name: Some("Wood".to_string()),
            pvp_damage_min: Some(17),
            pvp_damage_max: Some(17),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 75 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 25 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(10),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Rock".to_string(),
            description: "A basic tool for gathering.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "rock_item.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(3),
            primary_target_damage_max: Some(7),
            primary_target_yield_min: Some(3),
            primary_target_yield_max: Some(7),
            primary_target_type: Some(TargetType::Stone),
            primary_yield_resource_name: Some("Stone".to_string()),
            secondary_target_damage_min: Some(3),
            secondary_target_damage_max: Some(7),
            secondary_target_yield_min: Some(3),
            secondary_target_yield_max: Some(7),
            secondary_target_type: Some(TargetType::Tree),
            secondary_yield_resource_name: Some("Wood".to_string()),
            pvp_damage_min: Some(10),
            pvp_damage_max: Some(10),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Stone".to_string(), quantity: 5 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(1),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Wooden Spear".to_string(),
            description: "A sharpened stick. Better than fists.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "wooden_spear.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: Some(8),
            primary_target_damage_max: Some(12),
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(15),
            pvp_damage_max: Some(20),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 50 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Torch".to_string(),
            description: "Provides light and some warmth. Can be used as a makeshift weapon.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "torch.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: Some(300.0),
            primary_target_damage_min: Some(2),
            primary_target_damage_max: Some(4),
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: Some(5),
            pvp_damage_max: Some(5),
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 20 },
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },

        // --- PLACEABLES ---
        ItemDefinition {
            id: 0,
            name: "Camp Fire".to_string(),
            description: "A place to cook food and stay warm.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "campfire.png".to_string(),
            is_stackable: true,
            stack_size: 5,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 25 },
                CostIngredient { item_name: "Stone".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Wooden Storage Box".to_string(),
            description: "A simple container for storing items.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "wooden_storage_box.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Wood".to_string(), quantity: 100 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Sleeping Bag".to_string(),
            description: "A rolled-up bag for sleeping outdoors. Sets a respawn point.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "sleeping_bag.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 50 }
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },

        // --- ARMOR (CLOTH SET) ---
        ItemDefinition {
            id: 0,
            name: "Cloth Hood".to_string(),
            description: "Basic head covering.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_hood.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Head),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 20 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(10),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Shirt".to_string(),
            description: "Simple protection for the torso.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_shirt.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Chest),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 40 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Pants".to_string(),
            description: "Simple protection for the legs.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_pants.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Legs),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 30 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(15),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Gloves".to_string(),
            description: "Basic hand coverings.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_gloves.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Hands),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 15 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Boots".to_string(),
            description: "Simple footwear.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_boots.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Feet),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 15 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Burlap Backpack".to_string(),
            description: "A rough sack for carrying things. Increases inventory space.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "burlap_backpack.png".to_string(),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Back),
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![
                CostIngredient { item_name: "Cloth".to_string(), quantity: 30 },
                CostIngredient { item_name: "Plant Fiber".to_string(), quantity: 10 },
            ]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(20),
            consumable_health_gain: None,
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        
        // --- CONSUMABLES ---
        ItemDefinition {
            id: 0,
            name: "Mushroom".to_string(),
            description: "A raw mushroom. Edible, but maybe cook it?".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "mushroom.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(3.0),
            consumable_hunger_satiated: Some(15.0),
            consumable_thirst_quenched: Some(5.0),
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cooked Mushroom".to_string(),
            description: "A tasty cooked mushroom.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "cooked_mushroom.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(25.0),
            consumable_hunger_satiated: Some(15.0),
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Burnt Mushroom".to_string(),
            description: "Oops, cooked it too long. Barely edible.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "burnt_mushroom.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(-10.0),
            consumable_hunger_satiated: Some(-5.0),
            consumable_thirst_quenched: Some(-10.0),
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Corn".to_string(),
            description: "Raw corn. A bit tough to eat.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "corn.png".to_string(),
            is_stackable: true,
            stack_size: 20,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: None,
            crafting_output_quantity: None,
            crafting_time_secs: None,
            consumable_health_gain: Some(6.0),
            consumable_hunger_satiated: Some(75.0),
            consumable_thirst_quenched: Some(10.0),
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
        // --- NEW ITEM: Bandage ---
        ItemDefinition {
            id: 0,
            name: "Bandage".to_string(),
            description: "A simple bandage to patch up wounds.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "bandage.png".to_string(),
            is_stackable: true,
            stack_size: 10,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
            primary_target_damage_min: None,
            primary_target_damage_max: None,
            primary_target_yield_min: None,
            primary_target_yield_max: None,
            primary_target_type: None,
            primary_yield_resource_name: None,
            secondary_target_damage_min: None,
            secondary_target_damage_max: None,
            secondary_target_yield_min: None,
            secondary_target_yield_max: None,
            secondary_target_type: None,
            secondary_yield_resource_name: None,
            pvp_damage_min: None,
            pvp_damage_max: None,
            crafting_cost: Some(vec![CostIngredient { item_name: "Cloth".to_string(), quantity: 2 }]),
            crafting_output_quantity: Some(1),
            crafting_time_secs: Some(5),
            consumable_health_gain: Some(5.0),
            consumable_hunger_satiated: None,
            consumable_thirst_quenched: None,
            consumable_stamina_gain: None,
            consumable_duration_secs: None,
        },
    ];

    initial_items.into_iter().filter(|item_def| {
        !item_def.name.is_empty() 
    }).collect()
}
