use crate::items::{ItemDefinition, ItemCategory};
use crate::models::EquipmentSlotType;

pub fn get_initial_item_definitions() -> Vec<ItemDefinition> {
    let initial_items = vec![
        ItemDefinition {
            id: 0,
            name: "Wood".to_string(),
            description: "A sturdy piece of wood. Good for fuel.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "wood.png".to_string(),
            damage: None,
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: Some(10.0),
        },
        ItemDefinition {
            id: 0,
            name: "Stone".to_string(),
            description: "A chunk of rock.".to_string(),
            category: ItemCategory::Material,
            icon_asset_name: "stone.png".to_string(),
            damage: None,
            is_stackable: true,
            stack_size: 1000,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone Hatchet".to_string(),
            description: "A simple hatchet for chopping wood.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "wood_hatchet.png".to_string(),
            damage: Some(5),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Stone Pickaxe".to_string(),
            description: "A simple pickaxe for breaking rocks.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "pick_axe.png".to_string(),
            damage: Some(5),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Rock".to_string(),
            description: "A basic tool for gathering.".to_string(),
            category: ItemCategory::Tool,
            icon_asset_name: "rock_item.png".to_string(),
            damage: Some(1),
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Camp Fire".to_string(),
            description: "Provides warmth and light. Requires fuel.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "campfire.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Shirt".to_string(),
            description: "Simple protection for the torso.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_shirt.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Chest),
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Pants".to_string(),
            description: "Simple protection for the legs.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_pants.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Legs),
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Hood".to_string(),
            description: "Basic head covering.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_hood.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Head),
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Boots".to_string(),
            description: "Simple footwear.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_boots.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Feet),
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Cloth Gloves".to_string(),
            description: "Basic hand coverings.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "cloth_gloves.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Hands),
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Burlap Backpack".to_string(),
            description: "A rough sack for carrying things.".to_string(),
            category: ItemCategory::Armor,
            icon_asset_name: "burlap_backpack.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: true,
            equipment_slot_type: Some(EquipmentSlotType::Back),
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Mushroom".to_string(),
            description: "A common edible fungus.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "mushroom.png".to_string(),
            damage: None,
            is_stackable: true,
            stack_size: 50,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        // --- NEW Item: Wooden Storage Box ---
        ItemDefinition {
            id: 0, // Auto-incremented by SpacetimeDB
            name: "Wooden Storage Box".to_string(),
            description: "A simple container for storing items.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "wooden_storage_box.png".to_string(), // Assume this asset exists client-side
            damage: None,
            is_stackable: false, // Placeables are usually not stackable in inventory
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        // --- NEW Item: Sleeping Bag ---
        ItemDefinition {
            id: 0, // Auto-incremented
            name: "Sleeping Bag".to_string(),
            description: "A rolled-up bag for sleeping outdoors.".to_string(),
            category: ItemCategory::Placeable,
            icon_asset_name: "sleeping_bag.png".to_string(),
            damage: None,
            is_stackable: false,
            stack_size: 1,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
        ItemDefinition {
            id: 0,
            name: "Corn".to_string(),
            description: "A nutritious food source that can be eaten or used in cooking.".to_string(),
            category: ItemCategory::Consumable,
            icon_asset_name: "corn.png".to_string(),
            damage: None,
            is_stackable: true,
            stack_size: 50,
            is_equippable: false,
            equipment_slot_type: None,
            fuel_burn_duration_secs: None,
        },
    ];
    initial_items
}
